before:
  hooks:
    - go mod download
    - go generate ./...
project_name: "pipedream"
release:
  github:
    owner: Layer9Berlin
    name: PipeDream
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - pipes/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: pipedream

    tap:
      owner: Layer9Berlin
      name: homebrew-tap

    commit_author:
      name: Layer9GmbH
      email: hello@layer9.berlin

    folder: Formula

    homepage: "https://layer9.berlin/"

    description: "PipeDream - Maintainable script automation"

    license: "GPL-3.0-or-later"

    install: |
      bin.install "pipedream"
      include.install Dir["pipes/*"]
      system "#{bin}/pipedream"

    test: |
      system "#{bin}/pipedream --version"
nfpms:
  -
    id: pipedream
    package_name: pipedream

    vendor: Layer9 GmbH
    homepage: https://layer9.berlin
    maintainer: Layer9 GmbH <info@layer9.berlin>

    description: PipeDream - Maintainable script automation

    license: "GPL-3.0-or-later"

    formats:
      - apk
      - deb
      - rpm

    suggests:
      - git
      - zsh

    empty_folders:
      - /var/pipedream/pipes
