before:
  hooks:
    - go mod download
    - go generate ./...
project_name: "pipedream"
release:
  github:
    owner: Layer9Berlin
    name: PipeDream
builds:
  - id: pipedream_brew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X pipedream/src/version.Via=brew
      - -X pipedream/src/version.Version={{ .Version }}
      - -X pipedream/src/version.CommitHash={{ .Commit }}
      - -X pipedream/src/version.Date={{ .Date }}
      - -X pipedream/src/version.RepoChecksum={{ .Env.PIPEDREAM_INSTALL_SHASUM }}
  - id: pipedream_npm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X pipedream/src/version.Via=npm
      - -X pipedream/src/version.Version={{ .Version }}
      - -X pipedream/src/version.CommitHash={{ .Commit }}
      - -X pipedream/src/version.Date={{ .Date }}
      - -X pipedream/src/version.RepoChecksum={{ .Env.PIPEDREAM_INSTALL_SHASUM }}
  - id: pipedream_apt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X pipedream/src/version.Via=apt
      - -X pipedream/src/version.Version={{ .Version }}
      - -X pipedream/src/version.CommitHash={{ .Commit }}
      - -X pipedream/src/version.Date={{ .Date }}
      - -X pipedream/src/version.RepoChecksum={{ .Env.PIPEDREAM_INSTALL_SHASUM }}
  - id: semver-compare
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: util/semver-compare
  - id: traffic-light
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: util/traffic-light
archives:
  - id: npm_archive
    builds:
      - pipedream_npm
      - semver-compare
      - traffic-light
    files:
      - include/*
    name_template: "npm_{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: brew_archive
    builds:
      - pipedream_brew
      - semver-compare
      - traffic-light
    files:
      - include/*
    name_template: "brew_{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: pipedream
    ids:
      - brew_archive

    tap:
      owner: Layer9Berlin
      name: homebrew-tap

    commit_author:
      name: Layer9GmbH
      email: hello@layer9.berlin

    folder: Formula

    homepage: "https://layer9.berlin/"

    description: "PipeDream - Maintainable script automation"

    license: "GPL-3.0-or-later"

    install: |
      bin.install "pipedream"
      include.install Dir["include/*"]
      ln_s("#{include}/pipedream_pipes", "#{bin}", force: true)

    test: |
      system "#{bin}/pipedream --version"
nfpms:
  - id: pipedream
    builds:
      - pipedream_apt
      - semver-compare
      - traffic-light

    package_name: pipedream

    vendor: Layer9 GmbH
    homepage: https://layer9.berlin
    maintainer: Layer9 GmbH <info@layer9.berlin>

    description: PipeDream - Maintainable script automation

    license: "GPL-3.0-or-later"

    formats:
      - apk
      - deb
      - rpm

    suggests:
      - git
      - zsh
signs:
  - artifacts: checksum
    id: sign_checksums
    args: [ "--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}" ]
