name: Upload code coverage

on:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Go test
        run: go test ./src/... -coverprofile=test/coverage.out
      -
        name: Upload coverage
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./test/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}