name: Upload code coverage

on:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Go test
        run: go test ./src/... -coverprofile=test/coverage.out
      -
        name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
