name: PipeDream release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PIPEDREAM_RELEASE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PIPEDREAM_RELEASE_GPG_PASSPHRASE }}
      -
        name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PIPEDREAM_RELEASE_ACTION_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - 
        name: Create Packages file
        run: dpkg-scanpackages --multiversion --arch dist | gzip -c > dist/Packages.gz
      -
        name: Upload Packages file
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://github.com/Layer9Berlin/PipeDream/releases/download/${GITHUB_REF#refs/*/}
          asset_path: ./Packages.gz
          asset_name: Packages.gz
          asset_content_type: application/gzip